
---
apiVersion: v1
kind: Config
current-context: garden-kyma--c-6826c17-external
clusters:
- name: garden-kyma--c-6826c17-external
  cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ1akNDQWs2Z0F3SUJBZ0lRY2RNNW9QRE9aVHk5SlpxaEZlYUtmakFOQmdrcWhraUc5dzBCQVFzRkFEQU4KTVFzd0NRWURWUVFERXdKallUQWVGdzB5TkRBek1EWXhNVE14TVROYUZ3MHpOREF6TURZeE1UTXhNVE5hTUEweApDekFKQmdOVkJBTVRBbU5oTUlJQm9qQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FZOEFNSUlCaWdLQ0FZRUEyYUFRCkFjYWFJZVUzSElBZVNlbnZPVU1QTkM1ZWpTQ1ZlSVFKeHBMK2I3RmVBZ0E2NGpGQXl3Q1Vjb3YzZHhtSmgyMXQKV0tCc2ZzSTJET0hjZDhKSjVWNXNHTUszUVZ0RTl1d3lpakZoMUZHeTVPb1lrVlh2NXIzQ0hWUVA4UUxkK1ZTUwpvelIyRTNpQWFFYUs0K29SUlhyVlRVY3AyOW9SSGhTMU1Vd1NZV0ZYcTFnTVA3M0pCMU9wdW94WFI3TC9IYmFCCjIvK3lLdHhZQlVRZXVjWEp4emZOWFlYZExDVUVqOWZQZWhXaXpnZzZEMmRrcWJyMUJPK0plREFPbDJaSjc0M3MKeHNpY1R1bXFOL01zRUhFejJNalo0bHBCWVBnVE9pVmZHeDNYdWwrb1ZHc2NiV25MWlNiQlFMWi8rRnJLcWNxdAp3YTdjV2JrVXg4cXkvMUNWRFhFeTV4b25tQ3NrMnQwbVBaeGVzSDd2Z1NjU1FtK1FmK2J3TXR5MzNqVHFDSEhrCm1GTGJHQVYvTDd1UmhwRmw5cnBlTXhxZ1lGR0xZTVljbkk1UUp5UDE2d2J0SnZENDUzM0M5Yy83c0hGek1qcXcKVHBobXRhVGU1azVZNTlpN05KeTNGRlRKWXR2cXV1Sld4amFoNzJ3NHRNMGVYbDhCY1Y2bEpRcDRxZ0xIQWdNQgpBQUdqUWpCQU1BNEdBMVVkRHdFQi93UUVBd0lCcGpBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXCkJCUkJIMC9XTmQyb2xmeXRHTHlWMDlkc01yNGRLVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBWUVBZmVWWGY4Y3QKWlZDSVlTZVN5cVM5REY3ZkRrbFFBeHozejZ3cU5maisxTkJ2amVtUnNNNjlXbHVCaG85YzNOaXB0Yi9DeHF2ZgpjbnpJZHpzbDVNR0FDM012bkVCWlBiWm14Nk44UUtjbVdmcDFYQ0RXbEkrb3hBSUUrbUFlMXpQN0NPYUpKakVVCm1MMklOZlFKN1dZaVVsU2diVForN0k4MWpibUdoWmZKdlFJWkttQXY2RGxuMGFMdW1HQmU2VThoNHdCdDRDaUEKeitwOUhVVnZWWmdBZGNBY3R3dU9WSDkrYlplTGtjK001N3VsQ2NDbUk0TDExTjlwVmdzU1h0bWtGaXZ3dEhSSgpBZEFNK0lFbTFDMDVNUXQrdk42c3BwSi9ISHdxSWNXQ0piWU9ZUDdOQU9ZdHlMWWd3ZndiN1R0NTJWNmRTdDNNClczRGtjcXVsMDR0MVp6ZDYrVVErRHNrL2N5MGZWcWc3RFRhOEVQV0xMWnRqZVJ6WHB4ZW02akdUNXpGTzNLWHYKWFB1anVvWjRsRzZ6UVBuR1JYeFVjamRDcm1WdFRJQkJ5QUJjajMxaDF6UkQyakhHK2cxSGxJNUhRakRRdVpTZgpNVDNHS2JrOGI3RUkwZ01wMnVZSE4yTDcwYnk5S0xKQm9zZ2l2eWJXMHNyL2kxdUFSbWt3R0hnZwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://api.c-6826c17.kyma.ondemand.com
contexts:
- name: garden-kyma--c-6826c17-external
  context:
    cluster: garden-kyma--c-6826c17-external
    user: garden-kyma--c-6826c17-external
users:
- name: garden-kyma--c-6826c17-external
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - "--oidc-issuer-url=https://kyma.accounts.ondemand.com"
      - "--oidc-client-id=12b13a26-d993-4d0c-aa08-5f5852bbdff6"
      - "--oidc-extra-scope=email"
      - "--oidc-extra-scope=openid"
      command: kubectl-oidc_login
      installHint: |
        kubelogin plugin is required to proceed with authentication
        # Homebrew (macOS and Linux)
        brew install int128/kubelogin/kubelogin

        # Krew (macOS, Linux, Windows and ARM)
        kubectl krew install oidc-login

        # Chocolatey (Windows)
        choco install kubelogin
